### PR TITLE
test rust code in CI

### PR DESCRIPTION
**Pull request by MaxVerevkin**

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
Hm, the checkout is not recursive?

**Comment by MaxVerevkin** [comment]
I removed `build-linux-null-clang` because it doesn't seem to be applicable for this crate (we only have wayland on or wayland off).

**Comment by bvssvni** [comment]
Is this PR ready?

**Comment by MaxVerevkin** [comment]
Should be, it passes CI :)

**Comment by bvssvni** [comment]
Merging.

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
