### PR TITLE
include glfw as a submodule, update to 3.3.9

### LINKED ISSUE #3: Merge changes from glfw
This is a fork of the servo/glfw, which is a fork of the original glfw repo.

There might be Servo specific changes in this repo.

Should probably update with latest changes from the original repo.

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Closes  #3

### CODE REVIEW

**Comment by bvssvni** [comment]
Merging.

**Comment by bvssvni** [comment]
Thanks!

**Comment by MaxVerevkin** [comment]
The CI is failing but apparently that's because the CI was set up for GLFW, not the rust wrapper. Didn't catch this because of github's "first time contributor" thing :( I can send a PR with a CI which tests rust crate.

**Comment by bvssvni** [comment]
@MaxVerevkin I'm having problems on OSX. Could this be a submodule issue?

**Comment by MaxVerevkin** [comment]
>  Could this be a submodule issue?

Probably no. What exactly fails?

**Comment by bvssvni** [comment]
```
% cargo test
   Compiling glfw-sys v4.0.0+3.3.9 (/Users/sven/rust/glfw-sys)
error: failed to run custom build command for `glfw-sys v4.0.0+3.3.9 (/Users/sven/rust/glfw-sys)`

Caused by:
  process didn't exit successfully: `/Users/sven/rust/glfw-sys/target/debug/build/glfw-sys-6fa64f2c9a28559a/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-darwin = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_darwin = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-darwin = None
  CMAKE_GENERATOR_aarch64_apple_darwin = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-apple-darwin = None
  CMAKE_PREFIX_PATH_aarch64_apple_darwin = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-darwin = None
  CMAKE_aarch64_apple_darwin = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/Users/sven/rust/glfw-sys/target/debug/build/glfw-sys-2b3d4b4d29c9803c/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/Users/sven/rust/glfw-sys/glfw" "-DCMAKE_OSX_ARCHITECTURES=arm64" "-DGLFW_BUILD_EXAMPLES=OFF" "-DGLFW_BUILD_TESTS=OFF" "-DGLFW_BUILD_DOCS=OFF" "-DCMAKE_INSTALL_LIBDIR=lib" "-DGLFW_USE_WAYLAND=OFF" "-DCMAKE_INSTALL_PREFIX=/Users/sven/rust/glfw-sys/target/debug/build/glfw-sys-2b3d4b4d29c9803c/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  CMake Error: The source directory "/Users/sven/rust/glfw-sys/glfw" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  thread 'main' panicked at /Users/sven/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```

**Comment by MaxVerevkin** [comment]
@bvssvni  Can you try running `git submodule update --init --recursive`?

**Comment by bvssvni** [comment]
@MaxVerevkin Works, thanks!

**Comment by bvssvni** [comment]
@MaxVerevkin Can you fix CI?

**Comment by bvssvni** [comment]
I've merged the version bump, but not published yet so you can pull before you send the PR.

**Comment by MaxVerevkin** [comment]
> @MaxVerevkin Can you fix CI?

Yep, working on it.

**Comment by MaxVerevkin** [comment]
I think the readme should be update too.

**Pull request merged**
