### PR TITLE
Cargo 3.2.1

### PR DESCRIPTION
**Pull request by hadronized**
Update to GLFW 3.2.1. Changelog is [here](http://www.glfw.org/changelog.html).

### CODE REVIEW

**Comment by hadronized** [comment]
Ping PistonDevelopers/pistoncollaborator 

*Moderator edit: I removed the @ in front of PistonDevelopers to prevent notification spam*

**Comment by jhasse** [comment]
Please don't ping all of us like that, since there are many projects under PistonDevelopers. The one we want to watch, we'll select "watch" for. Just add a message "ping" to ping all people who are watching glfw-sys.

**Comment by retep998** [comment]
Updated to GLFW 3.2.1 and tagged. Will publish soon once someone confirms it looks good.
https://github.com/PistonDevelopers/glfw-sys/tree/3.2.1

**Comment by simnalamburt** [comment]
Uh... Isn't there a version of [glfw-sys 3.2.1](https://crates.io/crates/glfw-sys/3.2.1) already on crates.io?

**Comment by retep998** [comment]
@simnalamburt That's actually GLFW 3.2.0, but published under the version 3.2.1 to fix the repository link.

**Comment by hadronized** [comment]
I’m currently testing the tag you set, @retep998. It compiles and run correctly on Ubuntu LTS 16.04. I can’t test on my archlinux right now.

**Comment by retep998** [comment]
Published.

**Pull request closed without merging**
